# frozen_string_literal: true

require "digest"
require "logger"
require "json"

require "idempo/version"
require "idempo/errors"
require "idempo/configuration"
require "idempo/fingerprint"
require "idempo/storage/active_record"
require "idempo/storage/redis"
require "idempo/controller"
require "idempo/job"
require "idempo/webhook"
require "idempo/middleware"

# Load Railtie when Rails is present — wires up generators, rake tasks,
# and model autoloading.
require "idempo/railtie" if defined?(Rails)

module Idempo
  class << self
    # Yields the configuration object for setup in an initializer.
    #
    # @example
    #   Idempo.configure do |config|
    #     config.expiry               = 24.hours
    #     config.enforce_payload_match = true
    #   end
    #
    # @yieldparam config [Idempo::Configuration]
    def configure
      yield configuration
    end

    # Returns the memoized Configuration instance.
    # @return [Idempo::Configuration]
    def configuration
      @configuration ||= Configuration.new
    end

    # Convenience accessor — delegates to configuration.
    # @return [Logger]
    def logger
      configuration.logger
    end

    # Returns the configured backing store.
    # Uses configuration.store (set directly by the user) or falls back to
    # the ActiveRecord store.
    #
    # @return [Idempo::Storage::ActiveRecord, Idempo::Storage::Redis]
    def store
      configuration.store
    end

    # Deletes all expired idempotency records from the backing store.
    # Safe to call from a scheduled job (Sidekiq-cron, Heroku Scheduler, etc.).
    #
    # @example Rake task (generated by idempo:install)
    #   rake idempo:cleanup
    #
    # @return [Integer] number of records deleted
    def cleanup_expired!
      count = store.cleanup_expired!
      logger.info("[Idempo] cleanup_expired! removed #{count} record(s)")
      count
    end

    # Resets all memoized state. Used in tests and after reconfiguration.
    # @api private
    def reset!
      @configuration = nil
    end
  end
end